<?php

/**
 * Set of unit tests for Image class (for GD)
 */

class ImageGDTest extends ImageTestBase
{
    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function setUp(): void
    {
        if (!function_exists('gd_info')) {
            $this->markTestSkipped('gd extension not installed');
        }

        parent::setUp();
    }
}
