name: linter
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions:
        - '8.1'
        - '8.2'
        - '8.3' # nightly

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Get composer cache directory
      id: composer-cache-directory
      run: |
        composer config cache-dir
        echo "::set-output name=dir::$(composer config cache-dir)"
    - name: composer cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache-directory.outputs.dir }}
        key: php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php-${{ matrix.php-versions }}-composer

    - name: Compose setup
      run: composer install --no-interaction

    - name: Lint the code
      run: |
        PHP_CS_FIXER_IGNORE_ENV=1 \
          composer run lint
